mortnon:
  app:
    name: mortnon
    project-version: '@project.version@'
    mybatis-version: '@mybatis-plus.version@'
  captcha:
    enable: true
    type: arithmetic
    expire-seconds: 600
  shiro:
    enable: true
    anon:
      # 排除登录页面
      - /login,/logout,/login/password
      # 排除api页面
      - /api/**
      # 排除首页
      - /index/**
      # 排除logo
      - /favicon.ico
    filter-chain-definitions: |
      /resource/**=anon
      /upload/**=anon
      /captcha/**=anon
      /api/**=anon
      /demo/**=anon
  jwt:
    # token请求头名称
    token-name: token
    # jwt密钥
    secret: 666666
    # 发行人
    issuer: ${mortnon.app.name}
    # 观众
    audience: web
    # 默认过期时间1小时，单位：秒
    expire-second: 36000
    # 是否刷新token
    refresh-token: true
    # 刷新token的时间间隔，默认10分钟，单位：秒
    refresh-token-countdown: 600
    # 盐值校验，如果不加自定义盐值，则使用secret校验
    salt-check: true
    # 登录状态存储类型，local-内存ehcache存储，redis-redis存储
    login-storage-type: redis
  multi-tenant:
    # 开启多租户
    enable-multi-tenant: true
    # 默认租户
    default-tenant-id: mortnon
    # 租户列名
    tenant-id-column: tenant_id
    # 租户黑名单,名单中的表忽略租户信息,用逗号分割
    tenant-black-list: sys_role
  # 静态文件访问地址
  resource-handlers: |
    /api/**=classpath:/api/
    /index/**=classpath:/index/

springdoc:
  # swagger配置页面
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method
    #custom path for api docs
    url: /api/openapi.json

server:
  # 端口号
  port: 8080
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8


mybatis-plus:
  # 启动时是否检查MyBatis XML文件是否存在
  check-config-location: true
  # 支持统配符 * 或者 ; 分割
  type-aliases-package: org.mt.mortnon.*.enums
  # MyBatis原生配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 字段名称下划线转驼峰命名
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: assign_id
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0
    banner: false
  # mapper xml映射路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  config: classpath:config/logback.xml

spring:
  redis:
    timeout: 10s
    lettuce:
      pool:
        max-active: 200
        max-idle: 8
        max-wait: 10s
        min-idle: 2
      shutdown-timeout: 3s
    database: 0
    host: localhost
    password:
    port: 6379
  messages:
    basename: i18n/error_code,i18n/message
  # 激活环境，local:本机环境/dev：测试机/test：集成测试环境/prod：生产环境，在主pom里增加或修改
  profiles:
    active: @profileActive@
  # banner
  banner:
    charset: utf-8
    location: classpath:config/banner.txt
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      master:
        url:
        username:
        password:
      slave:
        enable: false
        url:
        username:
        password:
      # 初始链接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 配置获取链接超时等待时间
      max-wait: 5000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      webStat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: mortnon
        login-password: mortnon123!@#
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # 实体与表映射配置，以实体定义自动生成表，命名为下划线连接
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    # 服务模块
    devtools:
      restart:
        # 热部署开关
        enabled: true
    servlet:
      # 文件上传配置
      multipart:
        # 指定上传文件的临时目录
        location: ./upload_tmp
        # 单个文件最大值
        max-file-size: 55MB
        # 单个请求文件总计最大值
        max-request-size: 100MB